aws_region         = "eu-north-1"
vpc_cidr_block     = "10.0.0.0/16"
subnet_cidr_block  = "10.0.1.0/24"
availability_zone  = "eu-north-1a"
ami_id             = "ami-07c8c1b18ca66bb07"
instance_type      = "t3.micro"
s3_bucket_name    = "terraform.test.jai"
s3_key            = "terraform/state"
